name: Failing check

on:
    pull_request:

jobs:
    check:
        name: Failing
        runs-on: ubuntu-latest
        steps:
            -   name: delay
                run: sleep 120
            -   name: fail
                run: exit 1